### ISSUE TITLE
Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by kenilam** [shakyShane/html-injector#23]
Hi, @shakyShane 

I am using the bs-html-injector@3.0.2 in node@4.2.0. And encounter an error as follow:

```shell
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/Keni/Development/denali/pal-sites/retail-fixtures/node_modules/bs-html-injector/index.js:16:20)
...
```

I think the issue is relate to:
```shell
var _            = require("lodash");
```
https://github.com/shakyShane/html-injector/blob/master/index.js#L16

**Comment by kenilam** [comment]
Thanks @shakyShane
